# Generated by Django 3.1.4 on 2020-12-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestDevelopment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='score',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
