# Generated by Django 3.1.4 on 2020-12-15 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestDevelopment', '0002_people_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='gender',
        ),
    ]
