# Generated by Django 3.1.4 on 2020-12-15 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestDevelopment', '0003_remove_people_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': 'Student'},
        ),
        migrations.AlterModelTable(
            name='people',
            table='tb_people',
        ),
    ]
