# Generated by Django 3.1.4 on 2020-12-15 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestDevelopment', '0004_auto_20201215_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': ''},
        ),
    ]
