# Generated by Django 3.1.4 on 2020-12-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestDevelopment', '0005_auto_20201215_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDevelopment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='项目名称', max_length=200, unique=True, verbose_name='项目名称')),
                ('leader', models.CharField(help_text='项目负责人', max_length=50, verbose_name='项目负责人')),
                ('desc', models.TextField(blank=True, default='', help_text='项目描述', null=True, verbose_name='项目描述')),
            ],
            options={
                'db_table': 'tb_testdevelopment',
            },
        ),
    ]
